# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gif-info}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Kozák"]
  s.date = %q{2011-03-09}
  s.email = %q{martinkozak@martinkozak.net}
  s.executables = ["gif-dump", "gif-info"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "ajax-loader-0.gif",
    "ajax-loader.gif",
    "bin/gif-dump",
    "bin/gif-info",
    "lib/gif-info.rb",
    "lib/gif-info/block.rb",
    "lib/gif-info/blocks/application-extension.rb",
    "lib/gif-info/blocks/comment-extension.rb",
    "lib/gif-info/blocks/global-color-table.rb",
    "lib/gif-info/blocks/graphics-control-extension.rb",
    "lib/gif-info/blocks/header-block.rb",
    "lib/gif-info/blocks/image-data.rb",
    "lib/gif-info/blocks/image-descriptor.rb",
    "lib/gif-info/blocks/local-color-table.rb",
    "lib/gif-info/blocks/logical-screen-descriptor.rb",
    "lib/gif-info/blocks/plain-text-extension.rb",
    "lib/gif-info/blocks/trailer.rb",
    "lib/gif-info/body.rb",
    "lib/gif-info/color-table.rb",
    "lib/gif-info/data-block.rb",
    "lib/gif-info/dynamic-block.rb",
    "lib/gif-info/fixed-block.rb",
    "lib/gif-info/raw-block.rb",
    "test"
  ]
  s.homepage = %q{http://github.com/martinkozak/gif-info}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{Analyzer of the GIF image format. Performs complete analysis of internal GIF block structure and streams it as an objects stream with metainformations of each block. Also can interpret internal structure by providing the simple object-like interface to base image file informations. Works above seekable IO streams, so allows processing of the big files too. Doesn't perform LZW decompressing, returns raw data for both color tables and images.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<struct-fx>, [">= 0.1.1"])
      s.add_runtime_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<frozen-objects>, [">= 0.2.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<riot>, [">= 0.12.1"])
    else
      s.add_dependency(%q<struct-fx>, [">= 0.1.1"])
      s.add_dependency(%q<abstract>, [">= 1.0.0"])
      s.add_dependency(%q<frozen-objects>, [">= 0.2.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<riot>, [">= 0.12.1"])
    end
  else
    s.add_dependency(%q<struct-fx>, [">= 0.1.1"])
    s.add_dependency(%q<abstract>, [">= 1.0.0"])
    s.add_dependency(%q<frozen-objects>, [">= 0.2.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<riot>, [">= 0.12.1"])
  end
end

