#!/usr/bin/ruby
# encoding: utf-8
# (c) 2011 Martin Kozák (martinkozak@martinkozak.net)

$:.push("./lib")
require "gif-info"

f = GifInfo::analyze_file("./ajax-loader.gif")
p f
=begin
#100.times do
File.open("./ajax-loader.gif", "rb") do |io|
    GifInfo.parse(io) do |block|
        p block.class
        
        #if block.kind_of? GifInfo::LogicalScreenDescriptor
        #    p block.header.data.packed.data
        #end
    end
end
#end
=end
